#version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../workspace:/workspace
        depends_on:
            - php
        restart: unless-stopped
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        volumes:
            - ../workspace:/workspace
        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        #network_mode: service:db
        # Overrides default command so things don't shut down after the process ends.
        #command: sleep infinity
        restart: unless-stopped
    db:
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'dev'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'dev'
        volumes:
            - dbdata:/var/lib/mysql
        # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)
        ports:
            - 3306:3306
        restart: unless-stopped
volumes:
    dbdata: {}